name: Update Event Data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure script is executable
        run: chmod +x scripts/fetch_events.sh

      - name: Run fetch script
        run: ./scripts/fetch_events.sh

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/data/events.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update JSON data" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
