name: Update Event Data

on:
  schedule:
    - cron: "0 0 1 * *" # Runs on the 1st of every month at midnight UTC
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run fetch script
        run: pnpm fetch-events

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/data/events.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update events.json with latest data and timestamp" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}